name:                raytrace
version:             0.3.0
github:              "PlanarGraph/RayTraceInOneWeekend-Haskell"
license:             MIT
author:              "Nolan Tiffney"
maintainer:          "nolantiffney@gmail.com"
copyright:           "2019 Nolan Tiffney"

extra-source-files:
- README.md
  #ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PlanarGraph/RayTraceInOneWeekend-Haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  raytrace:
    main:                main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytrace

#tests:
#  rt-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - rt
